config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("everycheese.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'cheeses/',
        include('everycheese.cheeses.urls',
            namespace='cheeses'),
    ),
    path(
        'cheeses/',
        include('everycheese.cheeses.urls',
            namespace='Rating'),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

everycheese/cheeses/urls.py
from django.urls import path
from . import views
app_name = "cheeses"
urlpatterns = [
    path(
        route='',
        view=views.CheeseListView.as_view(),
        name='list'
    ),
    path(
        route='add/',
        view=views.CheeseCreateView.as_view(),
        name='add'
    ),
    path(
        route='update/<slug:slug>/',
        view=views.CheeseUpdateView.as_view(),
        name='update'
    ),

    path(
        route='<slug:slug>/',
        view=views.CheeseDetailView.as_view(),
        name='detail'
    ),
    path('<slug:slug>/delete/', views.CheeseDeleteView.as_view(), name='confirm_delete'),

    # URL pattern for the delete view function (no change needed here)
    path('<slug:slug>/delete/confirm/', views.delete_cheese, name='delete_cheese'),
    
]

everycheese/users/urls.py
from django.urls import path

from everycheese.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

everycheese/cheeses/models.py
from django.conf import settings
from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel
from django_countries.fields import CountryField
from django.urls import reverse
from django.core.validators import MaxValueValidator,MinValueValidator

class Cheese(TimeStampedModel):
    
    name = models.CharField("Name of Cheese", max_length=255, default="")
    slug = AutoSlugField("Cheese Address",
    unique=True, always_update=False, populate_from="name", default="")
    description = models.TextField("Description", blank=True)
    country_of_origin = CountryField("Country of Origin", blank=True)
    class Firmness(models.TextChoices):
        UNSPECIFIED = "unspecified", "Unspecified"
        SOFT = "soft", "Soft"
        SEMI_SOFT = "semi-soft", "Semi-Soft"
        SEMI_HARD = "semi-hard", "Semi-Hard"
        HARD = "hard", "Hard"
        # Other Fields Here...
    firmness = models.CharField("Firmness", max_length=20,
    choices=Firmness.choices, default=Firmness.UNSPECIFIED)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL
        )
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        """Return absolute URL to the Cheese Detail page."""
        return reverse(
            'cheeses:detail', kwargs={"slug": self.slug}
        )
    @property
    def average_rating(self):
        ratings = Rating.objects.all().filter(cheese=self)
        if ratings ==None:
            return 9
        total = 0
        count = 0
        for r in ratings:
            total += r.i_rating
            count += 1
        if count <= 0:
            return 0
        return total // count



    
    
class Rating(models.Model):
    i_rating = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL
    )
    cheese=models.ForeignKey(
        Cheese,
        null=True,
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return f"{self.i_rating}"
    
    

everycheese/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )
    
    bio = models.TextField("Bio", blank=True)

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

everycheese/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

everycheese/cheeses/views.py
import logging
log = logging.getLogger("root")
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, redirect
from .models import Cheese
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.urls import reverse_lazy
from django.http import request
from .models import Cheese, Rating  # Import the Rating model

class CheeseListView(ListView):
    model = Cheese
class CheeseDetailView(DetailView):
    model = Cheese
class CheeseCreateView(LoginRequiredMixin, CreateView):

    model = Cheese
    fields = [
        'name',
        'description',
        'firmness',
        'country_of_origin',
    ]
    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)
class CheeseUpdateView(LoginRequiredMixin, UpdateView):
    model = Cheese
    fields = [
        'name',
        'description',
        'firmness',
        'country_of_origin',
    ]
    action = "Update"


    def get_context_data(self, **kwargs):
        log.info("Hello from update")
        ctx = super(CheeseUpdateView, self).get_context_data(**kwargs)
        _slug = self.kwargs.get("slug")
        ch = Cheese.objects.all().filter(slug=_slug).first()

        if ch is None:
            ctx["rating"] = 0
            return ctx

        r = Rating.objects.all().filter(creator=self.request.user, cheese=ch).first()

        if r is not None:
            ctx["rating"] = r.i_rating
        else:
            ctx["rating"] = 0

        return ctx

    def form_valid(self, form):
        # Get the cheese being updated
        cheese = self.object

        # Get or create the rating for the current user and cheese
        rating, created = Rating.objects.get_or_create(creator=self.request.user, cheese=cheese)

        # Update the rating value based on the form data
        rating.i_rating = int(self.request.POST.get('rating'))  # Safely retrieve the rating value
        rating.save()

        return super().form_valid(form)

     


class CheeseDeleteView(LoginRequiredMixin, DeleteView):
    model = Cheese
    success_url = reverse_lazy('cheeses:list')  # Redirect to the list view after deletion

# Add the delete_cheese view function here
def delete_cheese(request, slug):
    cheese = Cheese.objects.get(slug=slug)
    
    if request.method == 'POST':
        # Delete the cheese if the request method is POST
        cheese.delete()
        return redirect('cheeses:list')  # Redirect to the list view after deletion
    
    return render(request, 'cheese_confirm_delete.html', {'cheese': cheese})

everycheese/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
        "bio",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

everycheese/templates/cheeses/cheese_confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete Cheese{% endblock title %}
{% block content %}
<h2>Confirm Delete</h2>
<p>Are you sure you want to delete the cheese "{{ cheese.name }}"?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Delete</button>
  <a  href="{% url 'cheeses:list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock content %}

everycheese/templates/cheeses/cheese_detail.html
{% extends "base.html" %}
{% block title %}Cheeses: {{ cheese.name }}{% endblock title %}
{% block content %}
<h2>{{ cheese.name }}</h2>
<p>
    <a class="btn btn-primary"
        href="{% url 'cheeses:update' cheese.slug %}"
        role="button">
            Update
        </a>
</p>
{% if cheese.firmness %}
    <p>Firmness: {{ cheese.get_firmness_display }}</p>
{% endif %}
{% if cheese.description %}
    <p>{{ cheese.description }}</p>
{% if cheese.country_of_origin %}
    <p>Country of Origin: {{ cheese.country_of_origin.name }}
    <img src="{{ cheese.country_of_origin.flag }}" />
    </p>
    {% if cheese.average_rating %}
<p>Rating: {{ cheese.average_rating }}/5</p>
{% endif %}
{% endif %}
{% endif %}
<hr/>
<h3>Submitted by
    <a href="{% url 'users:detail' cheese.creator.username %}">
        {{ cheese.creator.username }}
    </a>
</h3>
{% if cheese.creator.name %}
    <p>{{ cheese.creator.name }}</p>
{% endif %}
<h4>Cheese Rating:
    <p>
        <a class="btn btn-primary"
        href="{% url 'Rating:update' slug=cheese.slug %}"
        role="button">
        Update
        </a>
    </p>
</h4>
{% endblock content %}

everycheese/templates/cheeses/cheese_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    {{ view.action|default:"Add" }} Cheese
{% endblock title %}
{% block content %}
{% with action=view.action|default:"Add" %}
    <h1>{{ action }} Cheese</h1>
    
    <form method="post" action=".">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">  
            <label for="id_rating">Rating:</label>
            <input type="number" id="id_rating" name="rating" min="0" max="5" value="{{ rating }}" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">
            {{ action }}
        </button>
    </form>
{% endwith %}
{% endblock content %}
    

everycheese/templates/cheeses/cheese_list.html
{% extends "base.html" %}
{% block title %}Cheese List{% endblock title %}
{% block content %}
<h2>Cheese List</h2>
<table class ="table">
    <tr>
        <th>Cheese</th>
        <th>Country</th>
        <th>Command</th>
        <th>Rating</th>
    </tr>
    {% for cheese in cheese_list %}
    <tr>
        <td><a href="{% url 'cheeses:detail' cheese.slug %}">{{ cheese.name }}</a></td>
        <td><p>{{ cheese.country_of_origin}}</p></td>
        <td>
            <a href="{% url 'cheeses:confirm_delete' cheese.slug %}">Delete</a> | <a href="{% url 'cheeses:update' slug=cheese.slug %}">Update</a>
        </td>
        <td><p>{{ cheese.average_rating }}</p></td>
    </tr>
    {% endfor %}
</table>
<hr/>
<p>Don't see a cheese listed here?</p>
<p>
    <a class="btn btn-primary"
        href="{% url 'cheeses:add' %}" role="button">
     Add Cheese
    </a>
</p>
{% endblock content %}